### PR TITLE
closes #11

### LINKED ISSUE #11: Users should be able to see a range of dates where their space is available
As an user
So that I can decide on dates for my booking
I need to be able to see availability of space

### PR DESCRIPTION
**Pull request by mannieg**

### CODE REVIEW

**Comment by ogirginc** [comment]
🎱

**Comment by ogirginc** [comment]
💯

**Comment by ogirginc** [comment]
🔢

**Comment by mzishtiaq** [comment]
Good job guys... :shipit:

**Comment by alwinruby** [comment]
:shipit: 
YAY!

**Pull request merged**
