### PR TITLE
closes #32

### LINKED ISSUE #32: Showing User Links
Only show logout/spaces when user is logged in

### PR DESCRIPTION
**Pull request by mannieg**
…to non logged in users

### CODE REVIEW

**Comment by ogirginc** [comment]
okeyish but doesn't deserve squirrel

**Comment by mzishtiaq** [comment]
Just do it :shipit:

**Comment by alwinruby** [comment]
:shipit:

**Comment by mzishtiaq** [comment]
Don't let your dreams be dreams.

**Pull request merged**
